### ISSUE TITLE
what to set "mode" when i want a pie chart?

### ISSUE THREAD

**Issue by yanzixiang** [poetic/ember-highcharts-gauge#1]
i can NOT get it work when set it to "pie".

**Comment by JohnRodney** [comment]
`ember g route pie-chart`

put this

`{{high-charts mode=chartMode content=chartData chartOptions=chartOptions theme=theme}}`

In your template and then

`ember g controller pie-chart`

Inside your controller you can use the boilerplate code from the website: http://www.highcharts.com/demo/pie-basic.  You click the view options button and select all the code within the object instantiation.  aka from the chart Method down.  An Example of a working controller would look like this.

```
import Ember from 'ember';

export default Ember.Controller.extend({

  chartOptions: {
    chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false,
        type: 'pie'
    },
    title: {
        text: 'Browser market shares January, 2015 to May, 2015'
    },
    tooltip: {
        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
    },
    plotOptions: {
      pie: {
        allowPointSelect: true,
        cursor: 'pointer',
        dataLabels: {
          enabled: true,
          format: '<b>{point.name}</b>: {point.percentage:.1f} %',
          style: {
            color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
          }
        }
      }
    },
    series: [{
      name: "Brands",
      colorByPoint: true,
      data: [{
        name: "Microsoft Internet Explorer",
        y: 56.33
      }, {
        name: "Chrome",
        y: 24.03,
        sliced: true,
        selected: true
      }, {
        name: "Firefox",
        y: 10.38
      }, {
        name: "Safari",
        y: 4.77
      }, {
        name: "Opera",
        y: 0.91
      }, {
        name: "Proprietary or Undetectable",
        y: 0.2
      }]
    }]
  },
});
```

After this you can navigate to your route `/pie-chart` to see the results.  

For future internals of the library there are docs containing boilerplate for each chart type.  

You can view them all from http://www.highcharts.com/demo. 

if you would like to see a new chart module supported and configured through your configurations object please open a feature request.  As I would be interested in extending the library.
